// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		ElButton: typeof import('element-plus/es')['ElButton']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElRow: typeof import('element-plus/es')['ElRow']
		HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
		Loading: typeof import('element-plus/es')['ElLoadingDirective']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
	}
}

export {}
